# Generated by Django 4.2.16 on 2025-10-02 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agricola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('endereco', models.TextField(blank=True)),
                ('condicao', models.CharField(choices=[('diarista', 'Diarista'), ('temporario', 'Temporário'), ('registrado', 'Registrado')], max_length=20)),
                ('salario_registrado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salario_efetivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_hora_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_diaria_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('custo_rateado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordens_associadas', models.ManyToManyField(to='agricola.ordemservico')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
