# Generated by Django 4.2.16 on 2025-10-02 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('ncm', models.CharField(max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NfRecebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_nfe', models.CharField(max_length=44, unique=True)),
                ('xml_content', models.TextField()),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emitente_cnpj', models.CharField(max_length=18)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ciencia', 'Ciência'), ('rejeitada', 'Rejeitada'), ('pendente processamento', 'Pendente Processamento'), ('processada', 'Processada')], default='pendente', max_length=25)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('data_processamento', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_confirmada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscal.itemnf')),
                ('nf_recebida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscal.nfrecebida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemnf',
            name='nf_recebida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.nfrecebida'),
        ),
    ]
