# Generated by Django 4.2.16 on 2025-10-02 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('horas_registradas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('km_registrados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='notas/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField()),
                ('vida_util_anos', models.IntegerField()),
                ('depreciacao_anual', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.equipamento')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.maquina')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(choices=[('oleo_diesel', 'Óleo Diesel'), ('arla', 'Arla'), ('oleo_lubrificante', 'Óleo Lubrificante')], max_length=20)),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horimetro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_abastecimento', models.DateField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.equipamento')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
