# Generated by Django 4.2.16 on 2025-10-02 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fazendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('periodo_ideal_inicio', models.DateField()),
                ('periodo_ideal_fim', models.DateField()),
                ('ciclo_min', models.PositiveIntegerField(blank=True, help_text='Ciclo mínimo em dias (90-120)', null=True)),
                ('ciclo_max', models.PositiveIntegerField(blank=True, help_text='Ciclo máximo em dias (90-120)', null=True)),
                ('classificacao', models.CharField(blank=True, choices=[('grao', 'Grão'), ('leguminosa', 'Leguminosa'), ('hortalica', 'Hortaliça'), ('perene', 'Perene'), ('outra', 'Outra')], max_length=50, null=True)),
                ('necessidade_hidrica', models.DecimalField(blank=True, decimal_places=2, help_text='Necessidade hídrica em mm ou m³/ha', max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Dicas de manejo ou informações adicionais')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('tipo', models.CharField(choices=[('preparo', 'Preparo'), ('plantio', 'Plantio'), ('pulverizacao', 'Pulverização'), ('colheita', 'Colheita'), ('fertirrigacao', 'Fertirrigação'), ('irrigacao', 'Irrigação')], max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planejada', models.BooleanField(default=False)),
                ('produtividade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume_agua', models.DecimalField(blank=True, decimal_places=2, help_text='Volume de água em m³ (para irrigação/fertirrigação)', max_digits=10, null=True)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agricola.cultura')),
            ],
        ),
        migrations.CreateModel(
            name='UsoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('receita_por_ha', models.DecimalField(blank=True, decimal_places=2, help_text='Receita por hectare (ex: 200 ml/ha)', max_digits=8, null=True)),
                ('unidade_medida', models.CharField(blank=True, choices=[('ml/ha', 'ml/ha'), ('kg/ha', 'kg/ha'), ('l/ha', 'l/ha'), ('g/ha', 'g/ha')], max_length=20, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.insumo')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricola.ordemservico')),
            ],
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='insumos_usados',
            field=models.ManyToManyField(blank=True, through='agricola.UsoInsumo', to='estoque.insumo'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='talhao',
            field=models.ManyToManyField(to='fazendas.talhao'),
        ),
        migrations.CreateModel(
            name='Lavoura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantio', models.DateField()),
                ('irrigado', models.BooleanField(default=False, help_text='Marque se é irrigado (sequeiro se falso)')),
                ('ativo', models.BooleanField(default=True)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agricola.cultura')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lavouras', to='fazendas.talhao')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('fixo', 'Fixo'), ('temporario', 'Temporário'), ('diarista', 'Diarista')], max_length=20)),
                ('custo_diaria', models.DecimalField(decimal_places=2, default=0, help_text='Custo por dia ou hora', max_digits=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agricola_funcionarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
